### ISSUE TITLE
file miss: TrainingCenterDatabasev2.xsd.cs

### ISSUE THREAD

**Issue by faina09** [KennethEvans/VS-GpsUtils#1]
the file `TrainingCenterDatabasev2.xsd.cs` needed to build the solution is missed.

I tried to autogenerate it using xsd.exe ver 4.8.3928.0, starting from xsd in https://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd but it seems to be not compatible with the code (it generates a class `TrainingCenterDatabase_t` that is not compatible with `TrainingCenterDatabase` usesd by VS-GpsUtils)

**Comment by faina09** [comment]
I copied the file with same name from  [VS-Exercise-Analyzer]( https://github.com/KennethEvans/VS-Exercise-Analyzer) and it works

**Comment by KennethEvans** [comment]
The *.xsd.cs files were not tracked owing to the default VS .gitignore, and I did not catch it. It has been fixed, and they are now tracked. The version in Exercise Analyzer is the same.  It is not really needed there any longer however, as the implementation has been moved to the GpsUtils class library.
